sonar.projectKey=webchat-frontend
sonar.projectName=webchat-frontend
sonar.host.url=http://localhost:9000
sonar.scanner.version=8.1.0.6389
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/api/schema.d.ts,**/node_modules/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=src/api/schema.d.ts,src/main.tsx,src/telemetry/**
