/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация (№1)
         * @description Создаёт аккаунт (pending_email_confirmation) и ставит письмо со ссылкой подтверждения в очередь. Полное совпадение пары (username+email) на незавершённом аккаунте возобновляет регистрацию без дубля. Занятые username/email аккаунтом любого статуса → 409 с указанием поля, без раскрытия статуса держателя.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Повторная отправка письма регистрации (№2)
         * @description 202 всегда единообразно — не раскрывает существование/статус аккаунта. pending_email_confirmation → письмо email_verification_repeat; awaiting_password (вкл. истечение setupToken) → письмо password_setup со ссылкой /set-password; active/несуществующий email → письмо не отправляется. Источник 429: сначала бакеты (IP/email), затем cooldown 60 с на аккаунт (Retry-After = 60 − elapsed).
         */
        post: operations["resendRegistrationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтверждение email по ссылке (№3)
         * @description Поглощает одноразовый токен email_verification и выдаёт setupToken для задания пароля. Недействительная/использованная/истёкшая ссылка → единообразное 400 с предложением запросить новую (FR-012).
         */
        post: operations["confirmRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Задание пароля после подтверждения email (№4)
         * @description Поглощает setupToken, проверяет политику пароля FR-004 (8–128 символов; не пустой/пробельный; вне топ-листа тривиальных; не совпадает с username/email) и устанавливает Argon2id-хеш; аккаунт → active. Неверный пароль/несовпадение подтверждения не поглощают setupToken.
         */
        post: operations["setPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход по username или email и паролю (№5)
         * @description identifier = username ИЛИ email. Неверный пароль / несуществующий идентификатор → единая 401 «Invalid credentials» (тайминговая защита — фиктивный Argon2-хеш). Незавершённый аккаунт → 403 «завершите регистрацию». Успех → пара токенов: access JWT ES256 (5 мин) + opaque refresh (3 дня sliding).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ротация refresh-токена (№6)
         * @description Выдаёт новую пару токенов, старый refresh поглощается (single-use). Повторное применение ротированного токена → компрометация цепочки: 401, сессия и вся цепочка отозваны (FR-006). 401 единая, без различий (истёк / отозван / reuse).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход (№7, Bearer)
         * @description Отзывает сессию: access-токен должен быть действителен; переданный refresh отзывается, sid попадает в denylist (FR-011). Требует Authorization: Bearer.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запрос восстановления пароля (№8)
         * @description 202 всегда единообразно — не раскрывает существование email (US4-4). Для существующего аккаунта ставит письмо с одноразовой ссылкой reset-password (TTL 1 ч) в очередь; предыдущие ссылки аннулируются.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Установка нового пароля по ссылке восстановления (№9)
         * @description Поглощает одноразовый токен password_reset, устанавливает новый пароль (политика FR-004) и отзывает все сессии пользователя (FR-010). Нарушение политики/несовпадение подтверждения не поглощают ссылку.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь (№10, Bearer)
         * @description Минимальный защищённый ресурс для проверки границы аутентификации (US3, SC-002).
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Перечень включённых SSO-провайдеров (SSO §1)
         * @description Публичный перечень провайдеров для кнопок входа. Порядок — порядок объявления в конфигурации. Выключенные (enabled: false) и неизвестные провайдеры не видны. Пустой список валиден (SSO не настроен).
         */
        get: operations["listSsoProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Начало флоу входа через провайдера (SSO §2)
         * @description Создаёт флоу-контекст (state/PKCE S256/nonce, single-use, TTL 10 мин) и возвращает authorizationUrl для браузерного перехода на IdP — клиент обязан выполнить window.location.assign(authorizationUrl). Опциональный returnTo (только относительный путь) SPA сохраняет в sessionStorage до перехода и применяет после успешного обмена (SSO §4).
         */
        post: operations["ssoAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Завершение флоу — браузерный редирект с IdP (SSO §3)
         * @description Не JSON-API: вызывается браузером редиректом с IdP; тело ответа пустое. Изымает флоу-контекст sso:flow:&lt;state&gt; (GETDEL; отсутствующий или повторный state → отказ до любых эффектов), обменивает code у провайдера (общий deadline 5 с на callback), верифицирует ID-токен (подпись JWKS, iss/aud/exp/nonce, непустой уникальный sub) и применяет резолвинг идентичности. Все исходы логируются в auth_events.
         */
        get: operations["ssoCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обмен handshake-кода на сессию (SSO §4)
         * @description Поглощает одноразовый handshake-код из callback (GETDEL, TTL 2 мин) и создаёт сессию, полностью идентичную парольной (№5 из 002): тот же формат TokenPair, та же ротация refresh, тот же logout и доступ к API.
         */
        post: operations["ssoToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/link/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Начало флоу привязки провайдера (SSO §5, Bearer)
         * @description Аналогично SSO §2, но purpose=link: флоу-контекст связывается с текущим пользователем; результат — link-ветка callback (SSO §3, редирект на /settings/security). Повторная привязка уже своей идентичности — no-op success без дубля привязки.
         */
        post: operations["ssoLinkAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список привязанных внешних идентичностей (SSO §6, Bearer)
         * @description Привязки текущего пользователя; порядок — по linkedAt (возрастание). providerDisplayName берётся из конфигурации; null, если провайдер удалён из конфига (привязка сохраняется).
         */
        get: operations["listIdentities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/identities/{identityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Отвязка внешней идентичности (SSO §7, Bearer)
         * @description Удаляет привязку; существующие сессии не отзываются — блокируются только новые входы через этого провайдера. Отвязка последнего способа входа запрещена (US3-4): сначала задайте пароль.
         */
        delete: operations["unlinkIdentity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** @description Буквенно-цифровые границы; уникальность регистронезависимая (по lower()) */
            username: string;
            /** Format: email */
            email: string;
        };
        ResendRequest: {
            /** Format: email */
            email: string;
        };
        ConfirmRegistrationRequest: {
            /** @description Одноразовый токен email_verification (256-bit, base64url) */
            token: string;
        };
        SetPasswordRequest: {
            /** @description Одноразовый токен password_setup (256-bit, base64url) */
            setupToken: string;
            /** @description Политика FR-004: 8–128 символов; не пустой/пробельный; вне топ-листа тривиальных; ≠ username/email */
            password: string;
            confirmPassword: string;
        };
        LoginRequest: {
            /** @description username ИЛИ email */
            identifier: string;
            /** @description Без политики на входе — любой неверный пароль даёт единый 401; потолок 128 — DoS-защита */
            password: string;
        };
        RefreshRequest: {
            /** @description Opaque refresh-токен (256-bit, base64url) */
            refreshToken: string;
        };
        LogoutRequest: {
            /** @description Opaque refresh-токен (256-bit, base64url) */
            refreshToken: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            /** @description Одноразовый токен password_reset (256-bit, base64url) */
            token: string;
            /** @description Политика FR-004: 8–128 символов; не пустой/пробельный; вне топ-листа тривиальных; ≠ username/email */
            password: string;
            confirmPassword: string;
        };
        TokenPair: {
            /**
             * Format: jwt
             * @description Короткоживущий access-токен, JWT ES256 (TTL 5 мин)
             */
            accessToken: string;
            /** @description Opaque refresh-токен (256-bit, base64url, TTL 3 дня sliding); ротация при каждом использовании */
            refreshToken: string;
            /** @constant */
            tokenType: "Bearer";
            /** @description TTL access-токена, секунды */
            expiresInSec: number;
        };
        PublicUser: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            status: "pending_email_confirmation" | "awaiting_password" | "active";
            /** Format: date-time */
            createdAt: string;
        };
        /** @description RFC 9457: единая модель ошибок; расширения допускаются */
        Problem: {
            /** @description URI-reference на тип ошибки (опционально) */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Коды ошибок валидации по полям (в 400-ответах) */
            errors?: {
                [key: string]: string[];
            };
        };
        SsoProvider: {
            /** @description Стабильный код провайдера из конфигурации */
            id: string;
            /** @description Отображаемое имя для кнопки входа */
            displayName: string;
        };
        SsoProvidersResponse: {
            /** @description Включённые провайдеры в порядке конфигурации; пуст при ненастроенном SSO */
            providers: components["schemas"]["SsoProvider"][];
        };
        SsoAuthorizeRequest: {
            /** @description Код провайдера из GET /auth/sso/providers */
            providerId: string;
            /** @description Опциональный путь возврата внутри SPA (например /chat); только относительный путь — не-относительный или длиннее 512 символов → 400 invalid_format */
            returnTo?: string;
        };
        SsoLinkAuthorizeRequest: {
            /** @description Код провайдера для привязки к текущему пользователю */
            providerId: string;
        };
        SsoAuthorizeResponse: {
            /**
             * Format: uri
             * @description URL авторизации IdP: содержит state, nonce, PKCE code_challenge (S256); redirect_uri = {public-base-url}/api/v1/auth/sso/callback. Verifier клиенту не виден (server-side confidential client); клиент обязан выполнить браузерный переход
             */
            authorizationUrl: string;
        };
        SsoTokenRequest: {
            /** @description Одноразовый handshake-код из callback (TTL 2 мин) */
            code: string;
        };
        Identity: {
            /** Format: uuid */
            id: string;
            providerId: string;
            /** @description Отображаемое имя провайдера из конфигурации; null, если провайдер удалён из конфига */
            providerDisplayName?: string | null;
            /** @description Email от провайдера (последний известный) */
            email: string | null;
            /** Format: date-time */
            linkedAt: string;
        };
        IdentitiesResponse: {
            /** @description Привязки пользователя, упорядоченные по linkedAt */
            identities: components["schemas"]["Identity"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Аккаунт создан или незавершённая регистрация возобновлена; письмо поставлено в очередь */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка валидации полей (username/email); коды — в Problem.errors */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description username или email занят аккаунтом любого статуса; занятое поле указано, статус держателя не раскрывается */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP/email) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resendRegistrationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendRequest"];
            };
        };
        responses: {
            /** @description Принято единообразно (существование/статус аккаунта не раскрывается) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка валидации email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит (IP/email) или cooldown 60 с на аккаунт */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    confirmRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRegistrationRequest"];
            };
        };
        responses: {
            /** @description Email подтверждён; выдан setupToken для задания пароля (TTL 1 ч) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Одноразовый токен password_setup (256-bit, base64url) */
                        setupToken: string;
                        /** @constant */
                        setupTokenType: "password_setup";
                        /** @description TTL setupToken, секунды (3600) */
                        expiresInSec: number;
                    };
                };
            };
            /** @description Токен недействителен, использован или истёк (единообразно; предложение запросить новую ссылку) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Пароль установлен, аккаунт active */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Токен недействителен / нарушение политики пароля / несовпадение confirmPassword */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Пара токенов выдана; сессия создана */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"] & {
                        user: {
                            /** Format: uuid */
                            id: string;
                            username: string;
                            /** Format: email */
                            email: string;
                        };
                    };
                };
            };
            /** @description Единая обобщённая ошибка «Invalid credentials» (без различий причин) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Регистрация не завершена (подтвердите email / задайте пароль) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP/identifier) или блокировка подбора */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды (≈ остаток окна блокировки при подборе) */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Новая пара токенов (ротация) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Единая ошибка (истёк / отозван / reuse-detected — без различий) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен IP-лимит */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Сессия отозвана; оба токена недействительны */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не аутентифицирован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Принято всегда единообразно (существование email не раскрывается) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка валидации email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP/email) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Пароль изменён; все сессии отозваны */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Токен недействителен / нарушение политики пароля / несовпадение confirmPassword */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Данные аутентифицированного пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
            /** @description Не аутентифицирован (нет токена / истёк / отозван / недействителен — единообразно) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSsoProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Включённые провайдеры в порядке конфигурации */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoProvidersResponse"];
                };
            };
            /** @description Превышен лимит запросов (IP 30/1м) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ssoAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoAuthorizeRequest"];
            };
        };
        responses: {
            /** @description URL авторизации IdP (содержит state, nonce, PKCE code_challenge S256) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoAuthorizeResponse"];
                };
            };
            /** @description Невалидный returnTo: не-относительный путь или длина > 512 символов (errors: {returnTo: [invalid_format]}) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Провайдер неизвестен или выключен (единый ответ, без раскрытия перечня) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP 10/1м) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ssoCallback: {
        parameters: {
            query: {
                /** @description state из флоу-контекста (single-use) */
                state: string;
                /** @description Код авторизации IdP (присутствует при согласии пользователя) */
                code?: string;
                /** @description Ошибка от IdP (например access_denied) — маппится в sso_error=provider_error */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Редирект браузера на SPA-маршрут. Варианты Location: /sso/callback?code=&lt;handshake&gt;&amp;state=&lt;state&gt; — успешный вход (handshake — одноразовый код, ^[A-Za-z0-9_-]{43}$, TTL 2 мин, для обмена в SSO §4); /settings/security?linked=&lt;providerId&gt; — успешная привязка (link-флоу); /sso/callback?sso_error=&lt;code&gt; — отказ входа; /settings/security?sso_error=&lt;code&gt; — отказ привязки. Публичные коды sso_error: invalid_state, provider_disabled, provider_error, email_not_verified, email_conflict, registration_incomplete, identity_taken, rejected — без секретов и деталей владельцев. */
            302: {
                headers: {
                    /** @description Целевой маршрут SPA с code/linked или sso_error */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Превышен лимит запросов (IP 30/1м) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ssoToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoTokenRequest"];
            };
        };
        responses: {
            /** @description Пара токенов выдана; SSO-сессия создана */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"] & {
                        user: {
                            /** Format: uuid */
                            id: string;
                            username: string;
                            /** Format: email */
                            email: string;
                        };
                    };
                };
            };
            /** @description Код неизвестен, использован или истёк — единый ответ без различения причин (errors: {code: [invalid_code]}) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP 30/1м) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ssoLinkAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoLinkAuthorizeRequest"];
            };
        };
        responses: {
            /** @description URL авторизации IdP (содержит state, nonce, PKCE code_challenge S256) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoAuthorizeResponse"];
                };
            };
            /** @description Не аутентифицирован (нет токена / истёк / отозван / недействителен — единообразно) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Провайдер неизвестен или выключен (единый ответ, без раскрытия перечня) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Превышен лимит запросов (IP 10/1м) */
            429: {
                headers: {
                    /** @description Задержка до повтора, секунды */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список привязок пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitiesResponse"];
                };
            };
            /** @description Не аутентифицирован (нет токена / истёк / отозван / недействителен — единообразно) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unlinkIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор привязки */
                identityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Привязка удалена; сессии не отозваны */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не аутентифицирован (нет токена / истёк / отозван / недействителен — единообразно) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Идентичность не найдена или принадлежит другому пользователю (единый ответ, без раскрытия деталей) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Отвязка последнего способа входа запрещена (errors: {identity: [last_login_method]}; сначала задайте пароль) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
